// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: validating_policy_spec.proto

package v1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EvaluationMode represents the mode of policy evaluation
type EvaluationMode int32

const (
	EvaluationMode_EVALUATION_MODE_UNSPECIFIED EvaluationMode = 0
	EvaluationMode_EVALUATION_MODE_ENVOY       EvaluationMode = 1
	EvaluationMode_EVALUATION_MODE_JSON        EvaluationMode = 2
	EvaluationMode_EVALUATION_MODE_KUBERNETES  EvaluationMode = 3
	EvaluationMode_EVALUATION_MODE_HTTP        EvaluationMode = 4
)

// Enum value maps for EvaluationMode.
var (
	EvaluationMode_name = map[int32]string{
		0: "EVALUATION_MODE_UNSPECIFIED",
		1: "EVALUATION_MODE_ENVOY",
		2: "EVALUATION_MODE_JSON",
		3: "EVALUATION_MODE_KUBERNETES",
		4: "EVALUATION_MODE_HTTP",
	}
	EvaluationMode_value = map[string]int32{
		"EVALUATION_MODE_UNSPECIFIED": 0,
		"EVALUATION_MODE_ENVOY":       1,
		"EVALUATION_MODE_JSON":        2,
		"EVALUATION_MODE_KUBERNETES":  3,
		"EVALUATION_MODE_HTTP":        4,
	}
)

func (x EvaluationMode) Enum() *EvaluationMode {
	p := new(EvaluationMode)
	*p = x
	return p
}

func (x EvaluationMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EvaluationMode) Descriptor() protoreflect.EnumDescriptor {
	return file_validating_policy_spec_proto_enumTypes[0].Descriptor()
}

func (EvaluationMode) Type() protoreflect.EnumType {
	return &file_validating_policy_spec_proto_enumTypes[0]
}

func (x EvaluationMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EvaluationMode.Descriptor instead.
func (EvaluationMode) EnumDescriptor() ([]byte, []int) {
	return file_validating_policy_spec_proto_rawDescGZIP(), []int{0}
}

// FailurePolicyType defines how to handle failures for the admission policy
type FailurePolicyType int32

const (
	FailurePolicyType_FAILURE_POLICY_TYPE_UNSPECIFIED FailurePolicyType = 0
	FailurePolicyType_FAILURE_POLICY_TYPE_IGNORE      FailurePolicyType = 1
	FailurePolicyType_FAILURE_POLICY_TYPE_FAIL        FailurePolicyType = 2
)

// Enum value maps for FailurePolicyType.
var (
	FailurePolicyType_name = map[int32]string{
		0: "FAILURE_POLICY_TYPE_UNSPECIFIED",
		1: "FAILURE_POLICY_TYPE_IGNORE",
		2: "FAILURE_POLICY_TYPE_FAIL",
	}
	FailurePolicyType_value = map[string]int32{
		"FAILURE_POLICY_TYPE_UNSPECIFIED": 0,
		"FAILURE_POLICY_TYPE_IGNORE":      1,
		"FAILURE_POLICY_TYPE_FAIL":        2,
	}
)

func (x FailurePolicyType) Enum() *FailurePolicyType {
	p := new(FailurePolicyType)
	*p = x
	return p
}

func (x FailurePolicyType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FailurePolicyType) Descriptor() protoreflect.EnumDescriptor {
	return file_validating_policy_spec_proto_enumTypes[1].Descriptor()
}

func (FailurePolicyType) Type() protoreflect.EnumType {
	return &file_validating_policy_spec_proto_enumTypes[1]
}

func (x FailurePolicyType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FailurePolicyType.Descriptor instead.
func (FailurePolicyType) EnumDescriptor() ([]byte, []int) {
	return file_validating_policy_spec_proto_rawDescGZIP(), []int{1}
}

// ValidationAction specifies the action to be taken when the matched resource violates the policy
type ValidationAction int32

const (
	ValidationAction_VALIDATION_ACTION_UNSPECIFIED ValidationAction = 0
	ValidationAction_VALIDATION_ACTION_DENY        ValidationAction = 1
	ValidationAction_VALIDATION_ACTION_AUDIT       ValidationAction = 2
	ValidationAction_VALIDATION_ACTION_WARN        ValidationAction = 3
)

// Enum value maps for ValidationAction.
var (
	ValidationAction_name = map[int32]string{
		0: "VALIDATION_ACTION_UNSPECIFIED",
		1: "VALIDATION_ACTION_DENY",
		2: "VALIDATION_ACTION_AUDIT",
		3: "VALIDATION_ACTION_WARN",
	}
	ValidationAction_value = map[string]int32{
		"VALIDATION_ACTION_UNSPECIFIED": 0,
		"VALIDATION_ACTION_DENY":        1,
		"VALIDATION_ACTION_AUDIT":       2,
		"VALIDATION_ACTION_WARN":        3,
	}
)

func (x ValidationAction) Enum() *ValidationAction {
	p := new(ValidationAction)
	*p = x
	return p
}

func (x ValidationAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ValidationAction) Descriptor() protoreflect.EnumDescriptor {
	return file_validating_policy_spec_proto_enumTypes[2].Descriptor()
}

func (ValidationAction) Type() protoreflect.EnumType {
	return &file_validating_policy_spec_proto_enumTypes[2]
}

func (x ValidationAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ValidationAction.Descriptor instead.
func (ValidationAction) EnumDescriptor() ([]byte, []int) {
	return file_validating_policy_spec_proto_rawDescGZIP(), []int{2}
}

// MatchPolicyType defines how the "MatchResources" list is used to match incoming requests
type MatchPolicyType int32

const (
	MatchPolicyType_MATCH_POLICY_TYPE_UNSPECIFIED MatchPolicyType = 0
	MatchPolicyType_MATCH_POLICY_TYPE_EXACT       MatchPolicyType = 1
	MatchPolicyType_MATCH_POLICY_TYPE_EQUIVALENT  MatchPolicyType = 2
)

// Enum value maps for MatchPolicyType.
var (
	MatchPolicyType_name = map[int32]string{
		0: "MATCH_POLICY_TYPE_UNSPECIFIED",
		1: "MATCH_POLICY_TYPE_EXACT",
		2: "MATCH_POLICY_TYPE_EQUIVALENT",
	}
	MatchPolicyType_value = map[string]int32{
		"MATCH_POLICY_TYPE_UNSPECIFIED": 0,
		"MATCH_POLICY_TYPE_EXACT":       1,
		"MATCH_POLICY_TYPE_EQUIVALENT":  2,
	}
)

func (x MatchPolicyType) Enum() *MatchPolicyType {
	p := new(MatchPolicyType)
	*p = x
	return p
}

func (x MatchPolicyType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MatchPolicyType) Descriptor() protoreflect.EnumDescriptor {
	return file_validating_policy_spec_proto_enumTypes[3].Descriptor()
}

func (MatchPolicyType) Type() protoreflect.EnumType {
	return &file_validating_policy_spec_proto_enumTypes[3]
}

func (x MatchPolicyType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MatchPolicyType.Descriptor instead.
func (MatchPolicyType) EnumDescriptor() ([]byte, []int) {
	return file_validating_policy_spec_proto_rawDescGZIP(), []int{3}
}

// ValidatingPolicySpec is the specification of the desired behavior of the ValidatingPolicy.
type ValidatingPolicySpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// MatchConstraints specifies what resources this policy is designed to validate.
	// The AdmissionPolicy cares about a request if it matches _all_ Constraints.
	// Required.
	MatchConstraints *MatchResources `protobuf:"bytes,1,opt,name=match_constraints,json=matchConstraints,proto3,oneof" json:"match_constraints,omitempty"`
	// Validations contain CEL expressions which is used to apply the validation.
	// Validations and AuditAnnotations may not both be empty; a minimum of one Validations or AuditAnnotations is
	// required.
	Validations []*Validation `protobuf:"bytes,2,rep,name=validations,proto3" json:"validations,omitempty"`
	// failurePolicy defines how to handle failures for the admission policy. Failures can
	// occur from CEL expression parse errors, type check errors, runtime errors and invalid
	// or mis-configured policy definitions or bindings.
	//
	// failurePolicy does not define how validations that evaluate to false are handled.
	//
	// When failurePolicy is set to Fail, the validationActions field define how failures are enforced.
	//
	// Allowed values are Ignore or Fail. Defaults to Fail.
	FailurePolicy *FailurePolicyType `protobuf:"varint,3,opt,name=failure_policy,json=failurePolicy,proto3,enum=kyverno.http.v1alpha1.FailurePolicyType,oneof" json:"failure_policy,omitempty"`
	// auditAnnotations contains CEL expressions which are used to produce audit
	// annotations for the audit event of the API request.
	// validations and auditAnnotations may not both be empty; a least one of validations or auditAnnotations is
	// required.
	AuditAnnotations []*AuditAnnotation `protobuf:"bytes,4,rep,name=audit_annotations,json=auditAnnotations,proto3" json:"audit_annotations,omitempty"`
	// MatchConditions is a list of conditions that must be met for a request to be validated.
	// Match conditions filter requests that have already been matched by the rules,
	// namespaceSelector, and objectSelector. An empty list of matchConditions matches all requests.
	// There are a maximum of 64 match conditions allowed.
	MatchConditions []*MatchCondition `protobuf:"bytes,5,rep,name=match_conditions,json=matchConditions,proto3" json:"match_conditions,omitempty"`
	// Variables contain definitions of variables that can be used in composition of other expressions.
	// Each variable is defined as a named CEL expression.
	// The variables defined here will be available under `variables` in other expressions of the policy
	// except MatchConditions because MatchConditions are evaluated before the rest of the policy.
	Variables []*Variable `protobuf:"bytes,6,rep,name=variables,proto3" json:"variables,omitempty"`
	// AutogenConfiguration defines the configuration for the generation controller.
	Autogen *ValidatingPolicyAutogenConfiguration `protobuf:"bytes,7,opt,name=autogen,proto3,oneof" json:"autogen,omitempty"`
	// ValidationAction specifies the action to be taken when the matched resource violates the policy.
	// Required.
	ValidationActions []ValidationAction `protobuf:"varint,8,rep,packed,name=validation_actions,json=validationActions,proto3,enum=kyverno.http.v1alpha1.ValidationAction" json:"validation_actions,omitempty"`
	// WebhookConfiguration defines the configuration for the webhook.
	WebhookConfiguration *WebhookConfiguration `protobuf:"bytes,9,opt,name=webhook_configuration,json=webhookConfiguration,proto3,oneof" json:"webhook_configuration,omitempty"`
	// EvaluationConfiguration defines the configuration for the policy evaluation.
	Evaluation    *EvaluationConfiguration `protobuf:"bytes,10,opt,name=evaluation,proto3,oneof" json:"evaluation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidatingPolicySpec) Reset() {
	*x = ValidatingPolicySpec{}
	mi := &file_validating_policy_spec_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidatingPolicySpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidatingPolicySpec) ProtoMessage() {}

func (x *ValidatingPolicySpec) ProtoReflect() protoreflect.Message {
	mi := &file_validating_policy_spec_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidatingPolicySpec.ProtoReflect.Descriptor instead.
func (*ValidatingPolicySpec) Descriptor() ([]byte, []int) {
	return file_validating_policy_spec_proto_rawDescGZIP(), []int{0}
}

func (x *ValidatingPolicySpec) GetMatchConstraints() *MatchResources {
	if x != nil {
		return x.MatchConstraints
	}
	return nil
}

func (x *ValidatingPolicySpec) GetValidations() []*Validation {
	if x != nil {
		return x.Validations
	}
	return nil
}

func (x *ValidatingPolicySpec) GetFailurePolicy() FailurePolicyType {
	if x != nil && x.FailurePolicy != nil {
		return *x.FailurePolicy
	}
	return FailurePolicyType_FAILURE_POLICY_TYPE_UNSPECIFIED
}

func (x *ValidatingPolicySpec) GetAuditAnnotations() []*AuditAnnotation {
	if x != nil {
		return x.AuditAnnotations
	}
	return nil
}

func (x *ValidatingPolicySpec) GetMatchConditions() []*MatchCondition {
	if x != nil {
		return x.MatchConditions
	}
	return nil
}

func (x *ValidatingPolicySpec) GetVariables() []*Variable {
	if x != nil {
		return x.Variables
	}
	return nil
}

func (x *ValidatingPolicySpec) GetAutogen() *ValidatingPolicyAutogenConfiguration {
	if x != nil {
		return x.Autogen
	}
	return nil
}

func (x *ValidatingPolicySpec) GetValidationActions() []ValidationAction {
	if x != nil {
		return x.ValidationActions
	}
	return nil
}

func (x *ValidatingPolicySpec) GetWebhookConfiguration() *WebhookConfiguration {
	if x != nil {
		return x.WebhookConfiguration
	}
	return nil
}

func (x *ValidatingPolicySpec) GetEvaluation() *EvaluationConfiguration {
	if x != nil {
		return x.Evaluation
	}
	return nil
}

// EvaluationConfiguration defines the configuration for policy evaluation
type EvaluationConfiguration struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Mode is the mode of policy evaluation.
	// Allowed values are "Kubernetes" or "JSON".
	// Optional. Default value is "Kubernetes".
	Mode EvaluationMode `protobuf:"varint,1,opt,name=mode,proto3,enum=kyverno.http.v1alpha1.EvaluationMode" json:"mode,omitempty"`
	// Admission controls policy evaluation during admission.
	Admission *AdmissionConfiguration `protobuf:"bytes,2,opt,name=admission,proto3,oneof" json:"admission,omitempty"`
	// Background controls policy evaluation during background scan.
	Background    *BackgroundConfiguration `protobuf:"bytes,3,opt,name=background,proto3,oneof" json:"background,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvaluationConfiguration) Reset() {
	*x = EvaluationConfiguration{}
	mi := &file_validating_policy_spec_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluationConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluationConfiguration) ProtoMessage() {}

func (x *EvaluationConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_validating_policy_spec_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluationConfiguration.ProtoReflect.Descriptor instead.
func (*EvaluationConfiguration) Descriptor() ([]byte, []int) {
	return file_validating_policy_spec_proto_rawDescGZIP(), []int{1}
}

func (x *EvaluationConfiguration) GetMode() EvaluationMode {
	if x != nil {
		return x.Mode
	}
	return EvaluationMode_EVALUATION_MODE_UNSPECIFIED
}

func (x *EvaluationConfiguration) GetAdmission() *AdmissionConfiguration {
	if x != nil {
		return x.Admission
	}
	return nil
}

func (x *EvaluationConfiguration) GetBackground() *BackgroundConfiguration {
	if x != nil {
		return x.Background
	}
	return nil
}

// AdmissionConfiguration controls policy evaluation during admission
type AdmissionConfiguration struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Enabled controls if rules are applied during admission.
	// Optional. Default value is "true".
	Enabled       *wrapperspb.BoolValue `protobuf:"bytes,1,opt,name=enabled,proto3,oneof" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdmissionConfiguration) Reset() {
	*x = AdmissionConfiguration{}
	mi := &file_validating_policy_spec_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdmissionConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdmissionConfiguration) ProtoMessage() {}

func (x *AdmissionConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_validating_policy_spec_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdmissionConfiguration.ProtoReflect.Descriptor instead.
func (*AdmissionConfiguration) Descriptor() ([]byte, []int) {
	return file_validating_policy_spec_proto_rawDescGZIP(), []int{2}
}

func (x *AdmissionConfiguration) GetEnabled() *wrapperspb.BoolValue {
	if x != nil {
		return x.Enabled
	}
	return nil
}

// BackgroundConfiguration controls policy evaluation during background scan
type BackgroundConfiguration struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Enabled controls if rules are applied to existing resources during a background scan.
	// Optional. Default value is "true". The value must be set to "false" if the policy rule
	// uses variables that are only available in the admission review request (e.g. user name).
	Enabled       *wrapperspb.BoolValue `protobuf:"bytes,1,opt,name=enabled,proto3,oneof" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackgroundConfiguration) Reset() {
	*x = BackgroundConfiguration{}
	mi := &file_validating_policy_spec_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackgroundConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackgroundConfiguration) ProtoMessage() {}

func (x *BackgroundConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_validating_policy_spec_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackgroundConfiguration.ProtoReflect.Descriptor instead.
func (*BackgroundConfiguration) Descriptor() ([]byte, []int) {
	return file_validating_policy_spec_proto_rawDescGZIP(), []int{3}
}

func (x *BackgroundConfiguration) GetEnabled() *wrapperspb.BoolValue {
	if x != nil {
		return x.Enabled
	}
	return nil
}

// ValidatingPolicyAutogenConfiguration defines the configuration for the generation controller
type ValidatingPolicyAutogenConfiguration struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// PodControllers specifies whether to generate a pod controllers rules.
	PodControllers *PodControllersGenerationConfiguration `protobuf:"bytes,1,opt,name=pod_controllers,json=podControllers,proto3,oneof" json:"pod_controllers,omitempty"`
	// ValidatingAdmissionPolicy specifies whether to generate a Kubernetes ValidatingAdmissionPolicy.
	ValidatingAdmissionPolicy *VapGenerationConfiguration `protobuf:"bytes,2,opt,name=validating_admission_policy,json=validatingAdmissionPolicy,proto3,oneof" json:"validating_admission_policy,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *ValidatingPolicyAutogenConfiguration) Reset() {
	*x = ValidatingPolicyAutogenConfiguration{}
	mi := &file_validating_policy_spec_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidatingPolicyAutogenConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidatingPolicyAutogenConfiguration) ProtoMessage() {}

func (x *ValidatingPolicyAutogenConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_validating_policy_spec_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidatingPolicyAutogenConfiguration.ProtoReflect.Descriptor instead.
func (*ValidatingPolicyAutogenConfiguration) Descriptor() ([]byte, []int) {
	return file_validating_policy_spec_proto_rawDescGZIP(), []int{4}
}

func (x *ValidatingPolicyAutogenConfiguration) GetPodControllers() *PodControllersGenerationConfiguration {
	if x != nil {
		return x.PodControllers
	}
	return nil
}

func (x *ValidatingPolicyAutogenConfiguration) GetValidatingAdmissionPolicy() *VapGenerationConfiguration {
	if x != nil {
		return x.ValidatingAdmissionPolicy
	}
	return nil
}

// PodControllersGenerationConfiguration specifies pod controller generation settings
type PodControllersGenerationConfiguration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Controllers   []string               `protobuf:"bytes,1,rep,name=controllers,proto3" json:"controllers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PodControllersGenerationConfiguration) Reset() {
	*x = PodControllersGenerationConfiguration{}
	mi := &file_validating_policy_spec_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PodControllersGenerationConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodControllersGenerationConfiguration) ProtoMessage() {}

func (x *PodControllersGenerationConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_validating_policy_spec_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodControllersGenerationConfiguration.ProtoReflect.Descriptor instead.
func (*PodControllersGenerationConfiguration) Descriptor() ([]byte, []int) {
	return file_validating_policy_spec_proto_rawDescGZIP(), []int{5}
}

func (x *PodControllersGenerationConfiguration) GetControllers() []string {
	if x != nil {
		return x.Controllers
	}
	return nil
}

// VapGenerationConfiguration specifies ValidatingAdmissionPolicy generation settings
type VapGenerationConfiguration struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Enabled specifies whether to generate a Kubernetes ValidatingAdmissionPolicy.
	// Optional. Defaults to "false" if not specified.
	Enabled       *wrapperspb.BoolValue `protobuf:"bytes,1,opt,name=enabled,proto3,oneof" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VapGenerationConfiguration) Reset() {
	*x = VapGenerationConfiguration{}
	mi := &file_validating_policy_spec_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VapGenerationConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VapGenerationConfiguration) ProtoMessage() {}

func (x *VapGenerationConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_validating_policy_spec_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VapGenerationConfiguration.ProtoReflect.Descriptor instead.
func (*VapGenerationConfiguration) Descriptor() ([]byte, []int) {
	return file_validating_policy_spec_proto_rawDescGZIP(), []int{6}
}

func (x *VapGenerationConfiguration) GetEnabled() *wrapperspb.BoolValue {
	if x != nil {
		return x.Enabled
	}
	return nil
}

// WebhookConfiguration defines the configuration for the webhook
type WebhookConfiguration struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// TimeoutSeconds specifies the maximum time in seconds allowed to apply this policy.
	// After the configured time expires, the admission request may fail, or may simply ignore the policy results,
	// based on the failure policy. The default timeout is 10s, the value must be between 1 and 30 seconds.
	TimeoutSeconds *wrapperspb.Int32Value `protobuf:"bytes,1,opt,name=timeout_seconds,json=timeoutSeconds,proto3,oneof" json:"timeout_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *WebhookConfiguration) Reset() {
	*x = WebhookConfiguration{}
	mi := &file_validating_policy_spec_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebhookConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebhookConfiguration) ProtoMessage() {}

func (x *WebhookConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_validating_policy_spec_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebhookConfiguration.ProtoReflect.Descriptor instead.
func (*WebhookConfiguration) Descriptor() ([]byte, []int) {
	return file_validating_policy_spec_proto_rawDescGZIP(), []int{7}
}

func (x *WebhookConfiguration) GetTimeoutSeconds() *wrapperspb.Int32Value {
	if x != nil {
		return x.TimeoutSeconds
	}
	return nil
}

// MatchResources specifies what resources this policy is designed to validate
type MatchResources struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// NamespaceSelector decides whether to run the admission control policy on an object based
	// on whether the namespace for that object matches the selector. If the
	// object itself is a namespace, the matching is performed on
	// object.metadata.labels. If the object is another cluster scoped resource,
	// it never skips the policy.
	NamespaceSelector *LabelSelector `protobuf:"bytes,1,opt,name=namespace_selector,json=namespaceSelector,proto3,oneof" json:"namespace_selector,omitempty"`
	// ObjectSelector decides whether to run the validation based on if the
	// object has matching labels. objectSelector is evaluated against both
	// the oldObject and newObject that would be sent to the cel validation, and
	// is considered to match if either object matches the selector. A null
	// object (oldObject in the case of create, or newObject in the case of
	// delete) or an object that cannot have labels (like a
	// DeploymentRollback or a PodProxyOptions object) is not considered to
	// match.
	ObjectSelector *LabelSelector `protobuf:"bytes,2,opt,name=object_selector,json=objectSelector,proto3,oneof" json:"object_selector,omitempty"`
	// ResourceRules describes what operations on what resources/subresources the ValidatingAdmissionPolicy matches.
	// The policy cares about an operation if it matches _any_ Rule.
	ResourceRules []*NamedRuleWithOperations `protobuf:"bytes,3,rep,name=resource_rules,json=resourceRules,proto3" json:"resource_rules,omitempty"`
	// ExcludeResourceRules describes what operations on what resources/subresources the ValidatingAdmissionPolicy should not care about.
	// The exclude rules take precedence over include rules (if a resource matches both, it is excluded)
	ExcludeResourceRules []*NamedRuleWithOperations `protobuf:"bytes,4,rep,name=exclude_resource_rules,json=excludeResourceRules,proto3" json:"exclude_resource_rules,omitempty"`
	// matchPolicy defines how the "MatchResources" list is used to match incoming requests.
	// Allowed values are "Exact" or "Equivalent".
	MatchPolicy   *MatchPolicyType `protobuf:"varint,5,opt,name=match_policy,json=matchPolicy,proto3,enum=kyverno.http.v1alpha1.MatchPolicyType,oneof" json:"match_policy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchResources) Reset() {
	*x = MatchResources{}
	mi := &file_validating_policy_spec_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchResources) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchResources) ProtoMessage() {}

func (x *MatchResources) ProtoReflect() protoreflect.Message {
	mi := &file_validating_policy_spec_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchResources.ProtoReflect.Descriptor instead.
func (*MatchResources) Descriptor() ([]byte, []int) {
	return file_validating_policy_spec_proto_rawDescGZIP(), []int{8}
}

func (x *MatchResources) GetNamespaceSelector() *LabelSelector {
	if x != nil {
		return x.NamespaceSelector
	}
	return nil
}

func (x *MatchResources) GetObjectSelector() *LabelSelector {
	if x != nil {
		return x.ObjectSelector
	}
	return nil
}

func (x *MatchResources) GetResourceRules() []*NamedRuleWithOperations {
	if x != nil {
		return x.ResourceRules
	}
	return nil
}

func (x *MatchResources) GetExcludeResourceRules() []*NamedRuleWithOperations {
	if x != nil {
		return x.ExcludeResourceRules
	}
	return nil
}

func (x *MatchResources) GetMatchPolicy() MatchPolicyType {
	if x != nil && x.MatchPolicy != nil {
		return *x.MatchPolicy
	}
	return MatchPolicyType_MATCH_POLICY_TYPE_UNSPECIFIED
}

// LabelSelector represents a label selector
type LabelSelector struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// matchLabels is a map of {key,value} pairs. A single {key,value} in the matchLabels
	// map is equivalent to an element of matchExpressions, whose key field is "key", the
	// operator is "In", and the values array contains only "value". The requirements are ANDed.
	MatchLabels map[string]string `protobuf:"bytes,1,rep,name=match_labels,json=matchLabels,proto3" json:"match_labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// matchExpressions is a list of label selector requirements. The requirements are ANDed.
	MatchExpressions []*LabelSelectorRequirement `protobuf:"bytes,2,rep,name=match_expressions,json=matchExpressions,proto3" json:"match_expressions,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *LabelSelector) Reset() {
	*x = LabelSelector{}
	mi := &file_validating_policy_spec_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LabelSelector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LabelSelector) ProtoMessage() {}

func (x *LabelSelector) ProtoReflect() protoreflect.Message {
	mi := &file_validating_policy_spec_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LabelSelector.ProtoReflect.Descriptor instead.
func (*LabelSelector) Descriptor() ([]byte, []int) {
	return file_validating_policy_spec_proto_rawDescGZIP(), []int{9}
}

func (x *LabelSelector) GetMatchLabels() map[string]string {
	if x != nil {
		return x.MatchLabels
	}
	return nil
}

func (x *LabelSelector) GetMatchExpressions() []*LabelSelectorRequirement {
	if x != nil {
		return x.MatchExpressions
	}
	return nil
}

// LabelSelectorRequirement represents a selector requirement
type LabelSelectorRequirement struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// key is the label key that the selector applies to.
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// operator represents a key's relationship to a set of values.
	// Valid operators are In, NotIn, Exists and DoesNotExist.
	Operator string `protobuf:"bytes,2,opt,name=operator,proto3" json:"operator,omitempty"`
	// values is an array of string values. If the operator is In or NotIn,
	// the values array must be non-empty. If the operator is Exists or DoesNotExist,
	// the values array must be empty. This array is replaced during a strategic
	// merge patch.
	Values        []string `protobuf:"bytes,3,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LabelSelectorRequirement) Reset() {
	*x = LabelSelectorRequirement{}
	mi := &file_validating_policy_spec_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LabelSelectorRequirement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LabelSelectorRequirement) ProtoMessage() {}

func (x *LabelSelectorRequirement) ProtoReflect() protoreflect.Message {
	mi := &file_validating_policy_spec_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LabelSelectorRequirement.ProtoReflect.Descriptor instead.
func (*LabelSelectorRequirement) Descriptor() ([]byte, []int) {
	return file_validating_policy_spec_proto_rawDescGZIP(), []int{10}
}

func (x *LabelSelectorRequirement) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *LabelSelectorRequirement) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

func (x *LabelSelectorRequirement) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

// NamedRuleWithOperations represents a rule with operations
type NamedRuleWithOperations struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ResourceNames is an optional white list of names that the rule applies to.  An empty set means that everything is allowed.
	ResourceNames []string `protobuf:"bytes,1,rep,name=resource_names,json=resourceNames,proto3" json:"resource_names,omitempty"`
	// Rule represents the rule
	Rule          *Rule `protobuf:"bytes,2,opt,name=rule,proto3" json:"rule,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NamedRuleWithOperations) Reset() {
	*x = NamedRuleWithOperations{}
	mi := &file_validating_policy_spec_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NamedRuleWithOperations) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NamedRuleWithOperations) ProtoMessage() {}

func (x *NamedRuleWithOperations) ProtoReflect() protoreflect.Message {
	mi := &file_validating_policy_spec_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NamedRuleWithOperations.ProtoReflect.Descriptor instead.
func (*NamedRuleWithOperations) Descriptor() ([]byte, []int) {
	return file_validating_policy_spec_proto_rawDescGZIP(), []int{11}
}

func (x *NamedRuleWithOperations) GetResourceNames() []string {
	if x != nil {
		return x.ResourceNames
	}
	return nil
}

func (x *NamedRuleWithOperations) GetRule() *Rule {
	if x != nil {
		return x.Rule
	}
	return nil
}

// Rule represents a rule
type Rule struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// APIGroups is the API groups the resources belong to. '*' is all groups.
	// If '*' is present, the length of the slice must be one.
	ApiGroups []string `protobuf:"bytes,1,rep,name=api_groups,json=apiGroups,proto3" json:"api_groups,omitempty"`
	// APIVersions is the API versions the resources belong to. '*' is all versions.
	// If '*' is present, the length of the slice must be one.
	ApiVersions []string `protobuf:"bytes,2,rep,name=api_versions,json=apiVersions,proto3" json:"api_versions,omitempty"`
	// Resources is a list of resources this rule applies to.
	Resources []string `protobuf:"bytes,3,rep,name=resources,proto3" json:"resources,omitempty"`
	// Scope specifies the scope of this rule.
	// Valid values are "Cluster", "Namespaced", and "*"
	// "Cluster" means that only cluster-scoped resources will match this rule.
	// Namespaced objects are cluster-scoped, so "Namespaced" will not match any objects.
	// "*" means that there are no scope restrictions.
	// Subresources match the scope of their parent resource.
	// Default is "*".
	Scope         *string `protobuf:"bytes,4,opt,name=scope,proto3,oneof" json:"scope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Rule) Reset() {
	*x = Rule{}
	mi := &file_validating_policy_spec_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rule) ProtoMessage() {}

func (x *Rule) ProtoReflect() protoreflect.Message {
	mi := &file_validating_policy_spec_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rule.ProtoReflect.Descriptor instead.
func (*Rule) Descriptor() ([]byte, []int) {
	return file_validating_policy_spec_proto_rawDescGZIP(), []int{12}
}

func (x *Rule) GetApiGroups() []string {
	if x != nil {
		return x.ApiGroups
	}
	return nil
}

func (x *Rule) GetApiVersions() []string {
	if x != nil {
		return x.ApiVersions
	}
	return nil
}

func (x *Rule) GetResources() []string {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *Rule) GetScope() string {
	if x != nil && x.Scope != nil {
		return *x.Scope
	}
	return ""
}

// Validation represents a validation rule
type Validation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Expression represents the expression which will be evaluated by CEL.
	// ref: https://github.com/google/cel-spec
	// CEL expressions have access to the contents of the API request/response, organized into CEL variables as well as some other useful variables:
	Expression string `protobuf:"bytes,1,opt,name=expression,proto3" json:"expression,omitempty"`
	// Message represents the message displayed when validation fails. The message is required if the Expression contains
	// line breaks. The message must not contain line breaks.
	// If unset, the message is "failed rule: {Rule}".
	// e.g. "must be a URL with the host matching spec.host"
	// If the Expression contains line breaks. Message is required.
	// The message must not contain line breaks.
	// If unset, the message is "failed rule: {Rule}".
	Message *string `protobuf:"bytes,2,opt,name=message,proto3,oneof" json:"message,omitempty"`
	// Reason represents a machine-readable description of why this validation failed.
	// If this is the first validation in the list to fail, this reason will be used as the
	// CRD's overall validation error reason.  Must be a valid HTTP error reason or empty.
	Reason *string `protobuf:"bytes,3,opt,name=reason,proto3,oneof" json:"reason,omitempty"`
	// messageExpression declares a CEL expression that evaluates to the validation failure message that is returned when this rule fails.
	// Since messageExpression is used as a failure message, it must evaluate to a string.
	// If both message and messageExpression are present on a validation, then messageExpression will be used if validation fails.
	// If messageExpression results in a runtime error, the runtime error is logged, and the validation failure message is produced
	// as if the messageExpression field were unset. If messageExpression evaluates to an empty string, a string with only spaces, or a string
	// that contains line breaks, then the validation failure message will also be produced as if the messageExpression field were unset, and
	// the fact that messageExpression produced an empty string/string with only spaces/string with line breaks will be logged.
	// messageExpression has access to all the same variables as the `expression` except for 'authorizer' and 'authorizer.requestResource'.
	// Example:
	// "object.x must be less than max ("+string(params.max)+")"
	MessageExpression *string `protobuf:"bytes,4,opt,name=message_expression,json=messageExpression,proto3,oneof" json:"message_expression,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Validation) Reset() {
	*x = Validation{}
	mi := &file_validating_policy_spec_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Validation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Validation) ProtoMessage() {}

func (x *Validation) ProtoReflect() protoreflect.Message {
	mi := &file_validating_policy_spec_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Validation.ProtoReflect.Descriptor instead.
func (*Validation) Descriptor() ([]byte, []int) {
	return file_validating_policy_spec_proto_rawDescGZIP(), []int{13}
}

func (x *Validation) GetExpression() string {
	if x != nil {
		return x.Expression
	}
	return ""
}

func (x *Validation) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

func (x *Validation) GetReason() string {
	if x != nil && x.Reason != nil {
		return *x.Reason
	}
	return ""
}

func (x *Validation) GetMessageExpression() string {
	if x != nil && x.MessageExpression != nil {
		return *x.MessageExpression
	}
	return ""
}

// AuditAnnotation represents an audit annotation
type AuditAnnotation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// key specifies the audit annotation key. The audit annotation keys of
	// a ValidatingAdmissionPolicy must be unique. The key must be a qualified
	// name ([A-Za-z0-9][-A-Za-z0-9_.]*) no more than 63 bytes in length.
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// valueExpression represents the expression which is evaluated by CEL to
	// produce an audit annotation value. The expression must evaluate to either
	// a string or null value. If the expression evaluates to a string, the
	// audit annotation is included with the string value. If the expression
	// evaluates to null or empty string the audit annotation will be omitted.
	// The valueExpression may be no longer than 5kb in length.
	// If the result of the valueExpression is more than 10kb in length, it
	// will be truncated to 10kb.
	ValueExpression string `protobuf:"bytes,2,opt,name=value_expression,json=valueExpression,proto3" json:"value_expression,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AuditAnnotation) Reset() {
	*x = AuditAnnotation{}
	mi := &file_validating_policy_spec_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditAnnotation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditAnnotation) ProtoMessage() {}

func (x *AuditAnnotation) ProtoReflect() protoreflect.Message {
	mi := &file_validating_policy_spec_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditAnnotation.ProtoReflect.Descriptor instead.
func (*AuditAnnotation) Descriptor() ([]byte, []int) {
	return file_validating_policy_spec_proto_rawDescGZIP(), []int{14}
}

func (x *AuditAnnotation) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *AuditAnnotation) GetValueExpression() string {
	if x != nil {
		return x.ValueExpression
	}
	return ""
}

// MatchCondition represents a condition that must be met for a request to be validated
type MatchCondition struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name is an identifier for this match condition, used for strategic merging of MatchConditions,
	// as well as providing an identifier for logging purposes. A good name should be descriptive of
	// the associated expression.
	// Name must be a qualified name consisting of alphanumeric characters, '-', '_' or '.', and
	// must start and end with an alphanumeric character (e.g. 'MyName',  or 'my.name',  or
	// '123-abc', regex used for validation is '([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]') with an
	// optional DNS subdomain prefix and '/' (e.g. 'example.com/MyName')
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Expression represents the expression which will be evaluated by CEL. Must evaluate to bool.
	// CEL expressions have access to the contents of the AdmissionRequest and Authorizer, organized into CEL variables:
	Expression    string `protobuf:"bytes,2,opt,name=expression,proto3" json:"expression,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchCondition) Reset() {
	*x = MatchCondition{}
	mi := &file_validating_policy_spec_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchCondition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchCondition) ProtoMessage() {}

func (x *MatchCondition) ProtoReflect() protoreflect.Message {
	mi := &file_validating_policy_spec_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchCondition.ProtoReflect.Descriptor instead.
func (*MatchCondition) Descriptor() ([]byte, []int) {
	return file_validating_policy_spec_proto_rawDescGZIP(), []int{15}
}

func (x *MatchCondition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MatchCondition) GetExpression() string {
	if x != nil {
		return x.Expression
	}
	return ""
}

// Variable represents a variable definition
type Variable struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name is the name of the variable. The name must be a valid CEL identifier and unique among all variables.
	// The variable can be accessed in other expressions through `variables`
	// For example, if name is "foo", the variable will be available as `variables.foo`
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Expression is the expression that will be evaluated as the value of the variable.
	// The CEL expression has access to the same identifiers as the CEL expressions in Validation.
	Expression    string `protobuf:"bytes,2,opt,name=expression,proto3" json:"expression,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Variable) Reset() {
	*x = Variable{}
	mi := &file_validating_policy_spec_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Variable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Variable) ProtoMessage() {}

func (x *Variable) ProtoReflect() protoreflect.Message {
	mi := &file_validating_policy_spec_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Variable.ProtoReflect.Descriptor instead.
func (*Variable) Descriptor() ([]byte, []int) {
	return file_validating_policy_spec_proto_rawDescGZIP(), []int{16}
}

func (x *Variable) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Variable) GetExpression() string {
	if x != nil {
		return x.Expression
	}
	return ""
}

// Request message for validating policy operations
type ValidatingPolicyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The validating policy specification to process
	Spec *ValidatingPolicySpec `protobuf:"bytes,1,opt,name=spec,proto3" json:"spec,omitempty"`
	// Optional metadata for the request
	Metadata map[string]string `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Request ID for tracking
	RequestId     string `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidatingPolicyRequest) Reset() {
	*x = ValidatingPolicyRequest{}
	mi := &file_validating_policy_spec_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidatingPolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidatingPolicyRequest) ProtoMessage() {}

func (x *ValidatingPolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_validating_policy_spec_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidatingPolicyRequest.ProtoReflect.Descriptor instead.
func (*ValidatingPolicyRequest) Descriptor() ([]byte, []int) {
	return file_validating_policy_spec_proto_rawDescGZIP(), []int{17}
}

func (x *ValidatingPolicyRequest) GetSpec() *ValidatingPolicySpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *ValidatingPolicyRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ValidatingPolicyRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

// Response message for validating policy operations
type ValidatingPolicyResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Success indicates if the operation was successful
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Message provides additional information about the result
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Response metadata
	Metadata map[string]string `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Request ID for correlation
	RequestId     string `protobuf:"bytes,4,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidatingPolicyResponse) Reset() {
	*x = ValidatingPolicyResponse{}
	mi := &file_validating_policy_spec_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidatingPolicyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidatingPolicyResponse) ProtoMessage() {}

func (x *ValidatingPolicyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_validating_policy_spec_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidatingPolicyResponse.ProtoReflect.Descriptor instead.
func (*ValidatingPolicyResponse) Descriptor() ([]byte, []int) {
	return file_validating_policy_spec_proto_rawDescGZIP(), []int{18}
}

func (x *ValidatingPolicyResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ValidatingPolicyResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ValidatingPolicyResponse) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ValidatingPolicyResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

var File_validating_policy_spec_proto protoreflect.FileDescriptor

const file_validating_policy_spec_proto_rawDesc = "" +
	"\n" +
	"\x1cvalidating_policy_spec.proto\x12\x15kyverno.http.v1alpha1\x1a\x1egoogle/protobuf/wrappers.proto\"\xbe\a\n" +
	"\x14ValidatingPolicySpec\x12W\n" +
	"\x11match_constraints\x18\x01 \x01(\v2%.kyverno.http.v1alpha1.MatchResourcesH\x00R\x10matchConstraints\x88\x01\x01\x12C\n" +
	"\vvalidations\x18\x02 \x03(\v2!.kyverno.http.v1alpha1.ValidationR\vvalidations\x12T\n" +
	"\x0efailure_policy\x18\x03 \x01(\x0e2(.kyverno.http.v1alpha1.FailurePolicyTypeH\x01R\rfailurePolicy\x88\x01\x01\x12S\n" +
	"\x11audit_annotations\x18\x04 \x03(\v2&.kyverno.http.v1alpha1.AuditAnnotationR\x10auditAnnotations\x12P\n" +
	"\x10match_conditions\x18\x05 \x03(\v2%.kyverno.http.v1alpha1.MatchConditionR\x0fmatchConditions\x12=\n" +
	"\tvariables\x18\x06 \x03(\v2\x1f.kyverno.http.v1alpha1.VariableR\tvariables\x12Z\n" +
	"\aautogen\x18\a \x01(\v2;.kyverno.http.v1alpha1.ValidatingPolicyAutogenConfigurationH\x02R\aautogen\x88\x01\x01\x12V\n" +
	"\x12validation_actions\x18\b \x03(\x0e2'.kyverno.http.v1alpha1.ValidationActionR\x11validationActions\x12e\n" +
	"\x15webhook_configuration\x18\t \x01(\v2+.kyverno.http.v1alpha1.WebhookConfigurationH\x03R\x14webhookConfiguration\x88\x01\x01\x12S\n" +
	"\n" +
	"evaluation\x18\n" +
	" \x01(\v2..kyverno.http.v1alpha1.EvaluationConfigurationH\x04R\n" +
	"evaluation\x88\x01\x01B\x14\n" +
	"\x12_match_constraintsB\x11\n" +
	"\x0f_failure_policyB\n" +
	"\n" +
	"\b_autogenB\x18\n" +
	"\x16_webhook_configurationB\r\n" +
	"\v_evaluation\"\x98\x02\n" +
	"\x17EvaluationConfiguration\x129\n" +
	"\x04mode\x18\x01 \x01(\x0e2%.kyverno.http.v1alpha1.EvaluationModeR\x04mode\x12P\n" +
	"\tadmission\x18\x02 \x01(\v2-.kyverno.http.v1alpha1.AdmissionConfigurationH\x00R\tadmission\x88\x01\x01\x12S\n" +
	"\n" +
	"background\x18\x03 \x01(\v2..kyverno.http.v1alpha1.BackgroundConfigurationH\x01R\n" +
	"background\x88\x01\x01B\f\n" +
	"\n" +
	"_admissionB\r\n" +
	"\v_background\"_\n" +
	"\x16AdmissionConfiguration\x129\n" +
	"\aenabled\x18\x01 \x01(\v2\x1a.google.protobuf.BoolValueH\x00R\aenabled\x88\x01\x01B\n" +
	"\n" +
	"\b_enabled\"`\n" +
	"\x17BackgroundConfiguration\x129\n" +
	"\aenabled\x18\x01 \x01(\v2\x1a.google.protobuf.BoolValueH\x00R\aenabled\x88\x01\x01B\n" +
	"\n" +
	"\b_enabled\"\xbe\x02\n" +
	"$ValidatingPolicyAutogenConfiguration\x12j\n" +
	"\x0fpod_controllers\x18\x01 \x01(\v2<.kyverno.http.v1alpha1.PodControllersGenerationConfigurationH\x00R\x0epodControllers\x88\x01\x01\x12v\n" +
	"\x1bvalidating_admission_policy\x18\x02 \x01(\v21.kyverno.http.v1alpha1.VapGenerationConfigurationH\x01R\x19validatingAdmissionPolicy\x88\x01\x01B\x12\n" +
	"\x10_pod_controllersB\x1e\n" +
	"\x1c_validating_admission_policy\"I\n" +
	"%PodControllersGenerationConfiguration\x12 \n" +
	"\vcontrollers\x18\x01 \x03(\tR\vcontrollers\"c\n" +
	"\x1aVapGenerationConfiguration\x129\n" +
	"\aenabled\x18\x01 \x01(\v2\x1a.google.protobuf.BoolValueH\x00R\aenabled\x88\x01\x01B\n" +
	"\n" +
	"\b_enabled\"u\n" +
	"\x14WebhookConfiguration\x12I\n" +
	"\x0ftimeout_seconds\x18\x01 \x01(\v2\x1b.google.protobuf.Int32ValueH\x00R\x0etimeoutSeconds\x88\x01\x01B\x12\n" +
	"\x10_timeout_seconds\"\x87\x04\n" +
	"\x0eMatchResources\x12X\n" +
	"\x12namespace_selector\x18\x01 \x01(\v2$.kyverno.http.v1alpha1.LabelSelectorH\x00R\x11namespaceSelector\x88\x01\x01\x12R\n" +
	"\x0fobject_selector\x18\x02 \x01(\v2$.kyverno.http.v1alpha1.LabelSelectorH\x01R\x0eobjectSelector\x88\x01\x01\x12U\n" +
	"\x0eresource_rules\x18\x03 \x03(\v2..kyverno.http.v1alpha1.NamedRuleWithOperationsR\rresourceRules\x12d\n" +
	"\x16exclude_resource_rules\x18\x04 \x03(\v2..kyverno.http.v1alpha1.NamedRuleWithOperationsR\x14excludeResourceRules\x12N\n" +
	"\fmatch_policy\x18\x05 \x01(\x0e2&.kyverno.http.v1alpha1.MatchPolicyTypeH\x02R\vmatchPolicy\x88\x01\x01B\x15\n" +
	"\x13_namespace_selectorB\x12\n" +
	"\x10_object_selectorB\x0f\n" +
	"\r_match_policy\"\x87\x02\n" +
	"\rLabelSelector\x12X\n" +
	"\fmatch_labels\x18\x01 \x03(\v25.kyverno.http.v1alpha1.LabelSelector.MatchLabelsEntryR\vmatchLabels\x12\\\n" +
	"\x11match_expressions\x18\x02 \x03(\v2/.kyverno.http.v1alpha1.LabelSelectorRequirementR\x10matchExpressions\x1a>\n" +
	"\x10MatchLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"`\n" +
	"\x18LabelSelectorRequirement\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x1a\n" +
	"\boperator\x18\x02 \x01(\tR\boperator\x12\x16\n" +
	"\x06values\x18\x03 \x03(\tR\x06values\"q\n" +
	"\x17NamedRuleWithOperations\x12%\n" +
	"\x0eresource_names\x18\x01 \x03(\tR\rresourceNames\x12/\n" +
	"\x04rule\x18\x02 \x01(\v2\x1b.kyverno.http.v1alpha1.RuleR\x04rule\"\x8b\x01\n" +
	"\x04Rule\x12\x1d\n" +
	"\n" +
	"api_groups\x18\x01 \x03(\tR\tapiGroups\x12!\n" +
	"\fapi_versions\x18\x02 \x03(\tR\vapiVersions\x12\x1c\n" +
	"\tresources\x18\x03 \x03(\tR\tresources\x12\x19\n" +
	"\x05scope\x18\x04 \x01(\tH\x00R\x05scope\x88\x01\x01B\b\n" +
	"\x06_scope\"\xca\x01\n" +
	"\n" +
	"Validation\x12\x1e\n" +
	"\n" +
	"expression\x18\x01 \x01(\tR\n" +
	"expression\x12\x1d\n" +
	"\amessage\x18\x02 \x01(\tH\x00R\amessage\x88\x01\x01\x12\x1b\n" +
	"\x06reason\x18\x03 \x01(\tH\x01R\x06reason\x88\x01\x01\x122\n" +
	"\x12message_expression\x18\x04 \x01(\tH\x02R\x11messageExpression\x88\x01\x01B\n" +
	"\n" +
	"\b_messageB\t\n" +
	"\a_reasonB\x15\n" +
	"\x13_message_expression\"N\n" +
	"\x0fAuditAnnotation\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12)\n" +
	"\x10value_expression\x18\x02 \x01(\tR\x0fvalueExpression\"D\n" +
	"\x0eMatchCondition\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1e\n" +
	"\n" +
	"expression\x18\x02 \x01(\tR\n" +
	"expression\">\n" +
	"\bVariable\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1e\n" +
	"\n" +
	"expression\x18\x02 \x01(\tR\n" +
	"expression\"\x90\x02\n" +
	"\x17ValidatingPolicyRequest\x12?\n" +
	"\x04spec\x18\x01 \x01(\v2+.kyverno.http.v1alpha1.ValidatingPolicySpecR\x04spec\x12X\n" +
	"\bmetadata\x18\x02 \x03(\v2<.kyverno.http.v1alpha1.ValidatingPolicyRequest.MetadataEntryR\bmetadata\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\tR\trequestId\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x85\x02\n" +
	"\x18ValidatingPolicyResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12Y\n" +
	"\bmetadata\x18\x03 \x03(\v2=.kyverno.http.v1alpha1.ValidatingPolicyResponse.MetadataEntryR\bmetadata\x12\x1d\n" +
	"\n" +
	"request_id\x18\x04 \x01(\tR\trequestId\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*\xa0\x01\n" +
	"\x0eEvaluationMode\x12\x1f\n" +
	"\x1bEVALUATION_MODE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15EVALUATION_MODE_ENVOY\x10\x01\x12\x18\n" +
	"\x14EVALUATION_MODE_JSON\x10\x02\x12\x1e\n" +
	"\x1aEVALUATION_MODE_KUBERNETES\x10\x03\x12\x18\n" +
	"\x14EVALUATION_MODE_HTTP\x10\x04*v\n" +
	"\x11FailurePolicyType\x12#\n" +
	"\x1fFAILURE_POLICY_TYPE_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aFAILURE_POLICY_TYPE_IGNORE\x10\x01\x12\x1c\n" +
	"\x18FAILURE_POLICY_TYPE_FAIL\x10\x02*\x8a\x01\n" +
	"\x10ValidationAction\x12!\n" +
	"\x1dVALIDATION_ACTION_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16VALIDATION_ACTION_DENY\x10\x01\x12\x1b\n" +
	"\x17VALIDATION_ACTION_AUDIT\x10\x02\x12\x1a\n" +
	"\x16VALIDATION_ACTION_WARN\x10\x03*s\n" +
	"\x0fMatchPolicyType\x12!\n" +
	"\x1dMATCH_POLICY_TYPE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17MATCH_POLICY_TYPE_EXACT\x10\x01\x12 \n" +
	"\x1cMATCH_POLICY_TYPE_EQUIVALENT\x10\x022\x98\x01\n" +
	"\x17ValidatingPolicyService\x12}\n" +
	"\x16ValidatePoliciesStream\x12..kyverno.http.v1alpha1.ValidatingPolicyRequest\x1a/.kyverno.http.v1alpha1.ValidatingPolicyResponse(\x010\x01B@Z>github.com/kyverno/kyverno-http-authorizer/apis/proto/v1alpha1b\x06proto3"

var (
	file_validating_policy_spec_proto_rawDescOnce sync.Once
	file_validating_policy_spec_proto_rawDescData []byte
)

func file_validating_policy_spec_proto_rawDescGZIP() []byte {
	file_validating_policy_spec_proto_rawDescOnce.Do(func() {
		file_validating_policy_spec_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_validating_policy_spec_proto_rawDesc), len(file_validating_policy_spec_proto_rawDesc)))
	})
	return file_validating_policy_spec_proto_rawDescData
}

var file_validating_policy_spec_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_validating_policy_spec_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_validating_policy_spec_proto_goTypes = []any{
	(EvaluationMode)(0),                           // 0: kyverno.http.v1alpha1.EvaluationMode
	(FailurePolicyType)(0),                        // 1: kyverno.http.v1alpha1.FailurePolicyType
	(ValidationAction)(0),                         // 2: kyverno.http.v1alpha1.ValidationAction
	(MatchPolicyType)(0),                          // 3: kyverno.http.v1alpha1.MatchPolicyType
	(*ValidatingPolicySpec)(nil),                  // 4: kyverno.http.v1alpha1.ValidatingPolicySpec
	(*EvaluationConfiguration)(nil),               // 5: kyverno.http.v1alpha1.EvaluationConfiguration
	(*AdmissionConfiguration)(nil),                // 6: kyverno.http.v1alpha1.AdmissionConfiguration
	(*BackgroundConfiguration)(nil),               // 7: kyverno.http.v1alpha1.BackgroundConfiguration
	(*ValidatingPolicyAutogenConfiguration)(nil),  // 8: kyverno.http.v1alpha1.ValidatingPolicyAutogenConfiguration
	(*PodControllersGenerationConfiguration)(nil), // 9: kyverno.http.v1alpha1.PodControllersGenerationConfiguration
	(*VapGenerationConfiguration)(nil),            // 10: kyverno.http.v1alpha1.VapGenerationConfiguration
	(*WebhookConfiguration)(nil),                  // 11: kyverno.http.v1alpha1.WebhookConfiguration
	(*MatchResources)(nil),                        // 12: kyverno.http.v1alpha1.MatchResources
	(*LabelSelector)(nil),                         // 13: kyverno.http.v1alpha1.LabelSelector
	(*LabelSelectorRequirement)(nil),              // 14: kyverno.http.v1alpha1.LabelSelectorRequirement
	(*NamedRuleWithOperations)(nil),               // 15: kyverno.http.v1alpha1.NamedRuleWithOperations
	(*Rule)(nil),                                  // 16: kyverno.http.v1alpha1.Rule
	(*Validation)(nil),                            // 17: kyverno.http.v1alpha1.Validation
	(*AuditAnnotation)(nil),                       // 18: kyverno.http.v1alpha1.AuditAnnotation
	(*MatchCondition)(nil),                        // 19: kyverno.http.v1alpha1.MatchCondition
	(*Variable)(nil),                              // 20: kyverno.http.v1alpha1.Variable
	(*ValidatingPolicyRequest)(nil),               // 21: kyverno.http.v1alpha1.ValidatingPolicyRequest
	(*ValidatingPolicyResponse)(nil),              // 22: kyverno.http.v1alpha1.ValidatingPolicyResponse
	nil,                                           // 23: kyverno.http.v1alpha1.LabelSelector.MatchLabelsEntry
	nil,                                           // 24: kyverno.http.v1alpha1.ValidatingPolicyRequest.MetadataEntry
	nil,                                           // 25: kyverno.http.v1alpha1.ValidatingPolicyResponse.MetadataEntry
	(*wrapperspb.BoolValue)(nil),                  // 26: google.protobuf.BoolValue
	(*wrapperspb.Int32Value)(nil),                 // 27: google.protobuf.Int32Value
}
var file_validating_policy_spec_proto_depIdxs = []int32{
	12, // 0: kyverno.http.v1alpha1.ValidatingPolicySpec.match_constraints:type_name -> kyverno.http.v1alpha1.MatchResources
	17, // 1: kyverno.http.v1alpha1.ValidatingPolicySpec.validations:type_name -> kyverno.http.v1alpha1.Validation
	1,  // 2: kyverno.http.v1alpha1.ValidatingPolicySpec.failure_policy:type_name -> kyverno.http.v1alpha1.FailurePolicyType
	18, // 3: kyverno.http.v1alpha1.ValidatingPolicySpec.audit_annotations:type_name -> kyverno.http.v1alpha1.AuditAnnotation
	19, // 4: kyverno.http.v1alpha1.ValidatingPolicySpec.match_conditions:type_name -> kyverno.http.v1alpha1.MatchCondition
	20, // 5: kyverno.http.v1alpha1.ValidatingPolicySpec.variables:type_name -> kyverno.http.v1alpha1.Variable
	8,  // 6: kyverno.http.v1alpha1.ValidatingPolicySpec.autogen:type_name -> kyverno.http.v1alpha1.ValidatingPolicyAutogenConfiguration
	2,  // 7: kyverno.http.v1alpha1.ValidatingPolicySpec.validation_actions:type_name -> kyverno.http.v1alpha1.ValidationAction
	11, // 8: kyverno.http.v1alpha1.ValidatingPolicySpec.webhook_configuration:type_name -> kyverno.http.v1alpha1.WebhookConfiguration
	5,  // 9: kyverno.http.v1alpha1.ValidatingPolicySpec.evaluation:type_name -> kyverno.http.v1alpha1.EvaluationConfiguration
	0,  // 10: kyverno.http.v1alpha1.EvaluationConfiguration.mode:type_name -> kyverno.http.v1alpha1.EvaluationMode
	6,  // 11: kyverno.http.v1alpha1.EvaluationConfiguration.admission:type_name -> kyverno.http.v1alpha1.AdmissionConfiguration
	7,  // 12: kyverno.http.v1alpha1.EvaluationConfiguration.background:type_name -> kyverno.http.v1alpha1.BackgroundConfiguration
	26, // 13: kyverno.http.v1alpha1.AdmissionConfiguration.enabled:type_name -> google.protobuf.BoolValue
	26, // 14: kyverno.http.v1alpha1.BackgroundConfiguration.enabled:type_name -> google.protobuf.BoolValue
	9,  // 15: kyverno.http.v1alpha1.ValidatingPolicyAutogenConfiguration.pod_controllers:type_name -> kyverno.http.v1alpha1.PodControllersGenerationConfiguration
	10, // 16: kyverno.http.v1alpha1.ValidatingPolicyAutogenConfiguration.validating_admission_policy:type_name -> kyverno.http.v1alpha1.VapGenerationConfiguration
	26, // 17: kyverno.http.v1alpha1.VapGenerationConfiguration.enabled:type_name -> google.protobuf.BoolValue
	27, // 18: kyverno.http.v1alpha1.WebhookConfiguration.timeout_seconds:type_name -> google.protobuf.Int32Value
	13, // 19: kyverno.http.v1alpha1.MatchResources.namespace_selector:type_name -> kyverno.http.v1alpha1.LabelSelector
	13, // 20: kyverno.http.v1alpha1.MatchResources.object_selector:type_name -> kyverno.http.v1alpha1.LabelSelector
	15, // 21: kyverno.http.v1alpha1.MatchResources.resource_rules:type_name -> kyverno.http.v1alpha1.NamedRuleWithOperations
	15, // 22: kyverno.http.v1alpha1.MatchResources.exclude_resource_rules:type_name -> kyverno.http.v1alpha1.NamedRuleWithOperations
	3,  // 23: kyverno.http.v1alpha1.MatchResources.match_policy:type_name -> kyverno.http.v1alpha1.MatchPolicyType
	23, // 24: kyverno.http.v1alpha1.LabelSelector.match_labels:type_name -> kyverno.http.v1alpha1.LabelSelector.MatchLabelsEntry
	14, // 25: kyverno.http.v1alpha1.LabelSelector.match_expressions:type_name -> kyverno.http.v1alpha1.LabelSelectorRequirement
	16, // 26: kyverno.http.v1alpha1.NamedRuleWithOperations.rule:type_name -> kyverno.http.v1alpha1.Rule
	4,  // 27: kyverno.http.v1alpha1.ValidatingPolicyRequest.spec:type_name -> kyverno.http.v1alpha1.ValidatingPolicySpec
	24, // 28: kyverno.http.v1alpha1.ValidatingPolicyRequest.metadata:type_name -> kyverno.http.v1alpha1.ValidatingPolicyRequest.MetadataEntry
	25, // 29: kyverno.http.v1alpha1.ValidatingPolicyResponse.metadata:type_name -> kyverno.http.v1alpha1.ValidatingPolicyResponse.MetadataEntry
	21, // 30: kyverno.http.v1alpha1.ValidatingPolicyService.ValidatePoliciesStream:input_type -> kyverno.http.v1alpha1.ValidatingPolicyRequest
	22, // 31: kyverno.http.v1alpha1.ValidatingPolicyService.ValidatePoliciesStream:output_type -> kyverno.http.v1alpha1.ValidatingPolicyResponse
	31, // [31:32] is the sub-list for method output_type
	30, // [30:31] is the sub-list for method input_type
	30, // [30:30] is the sub-list for extension type_name
	30, // [30:30] is the sub-list for extension extendee
	0,  // [0:30] is the sub-list for field type_name
}

func init() { file_validating_policy_spec_proto_init() }
func file_validating_policy_spec_proto_init() {
	if File_validating_policy_spec_proto != nil {
		return
	}
	file_validating_policy_spec_proto_msgTypes[0].OneofWrappers = []any{}
	file_validating_policy_spec_proto_msgTypes[1].OneofWrappers = []any{}
	file_validating_policy_spec_proto_msgTypes[2].OneofWrappers = []any{}
	file_validating_policy_spec_proto_msgTypes[3].OneofWrappers = []any{}
	file_validating_policy_spec_proto_msgTypes[4].OneofWrappers = []any{}
	file_validating_policy_spec_proto_msgTypes[6].OneofWrappers = []any{}
	file_validating_policy_spec_proto_msgTypes[7].OneofWrappers = []any{}
	file_validating_policy_spec_proto_msgTypes[8].OneofWrappers = []any{}
	file_validating_policy_spec_proto_msgTypes[12].OneofWrappers = []any{}
	file_validating_policy_spec_proto_msgTypes[13].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_validating_policy_spec_proto_rawDesc), len(file_validating_policy_spec_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_validating_policy_spec_proto_goTypes,
		DependencyIndexes: file_validating_policy_spec_proto_depIdxs,
		EnumInfos:         file_validating_policy_spec_proto_enumTypes,
		MessageInfos:      file_validating_policy_spec_proto_msgTypes,
	}.Build()
	File_validating_policy_spec_proto = out.File
	file_validating_policy_spec_proto_goTypes = nil
	file_validating_policy_spec_proto_depIdxs = nil
}
