// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: validatingpolicy.proto

package v1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// FailurePolicyType defines failure handling behavior
type FailurePolicyType int32

const (
	FailurePolicyType_FAILURE_POLICY_TYPE_UNSPECIFIED FailurePolicyType = 0
	FailurePolicyType_FAILURE_POLICY_TYPE_IGNORE      FailurePolicyType = 1
	FailurePolicyType_FAILURE_POLICY_TYPE_FAIL        FailurePolicyType = 2
)

// Enum value maps for FailurePolicyType.
var (
	FailurePolicyType_name = map[int32]string{
		0: "FAILURE_POLICY_TYPE_UNSPECIFIED",
		1: "FAILURE_POLICY_TYPE_IGNORE",
		2: "FAILURE_POLICY_TYPE_FAIL",
	}
	FailurePolicyType_value = map[string]int32{
		"FAILURE_POLICY_TYPE_UNSPECIFIED": 0,
		"FAILURE_POLICY_TYPE_IGNORE":      1,
		"FAILURE_POLICY_TYPE_FAIL":        2,
	}
)

func (x FailurePolicyType) Enum() *FailurePolicyType {
	p := new(FailurePolicyType)
	*p = x
	return p
}

func (x FailurePolicyType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FailurePolicyType) Descriptor() protoreflect.EnumDescriptor {
	return file_validatingpolicy_proto_enumTypes[0].Descriptor()
}

func (FailurePolicyType) Type() protoreflect.EnumType {
	return &file_validatingpolicy_proto_enumTypes[0]
}

func (x FailurePolicyType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FailurePolicyType.Descriptor instead.
func (FailurePolicyType) EnumDescriptor() ([]byte, []int) {
	return file_validatingpolicy_proto_rawDescGZIP(), []int{0}
}

// ValidationAction defines actions for policy violations
type ValidationAction int32

const (
	ValidationAction_VALIDATION_ACTION_UNSPECIFIED ValidationAction = 0
	ValidationAction_VALIDATION_ACTION_DENY        ValidationAction = 1
	ValidationAction_VALIDATION_ACTION_AUDIT       ValidationAction = 2
	ValidationAction_VALIDATION_ACTION_WARN        ValidationAction = 3
)

// Enum value maps for ValidationAction.
var (
	ValidationAction_name = map[int32]string{
		0: "VALIDATION_ACTION_UNSPECIFIED",
		1: "VALIDATION_ACTION_DENY",
		2: "VALIDATION_ACTION_AUDIT",
		3: "VALIDATION_ACTION_WARN",
	}
	ValidationAction_value = map[string]int32{
		"VALIDATION_ACTION_UNSPECIFIED": 0,
		"VALIDATION_ACTION_DENY":        1,
		"VALIDATION_ACTION_AUDIT":       2,
		"VALIDATION_ACTION_WARN":        3,
	}
)

func (x ValidationAction) Enum() *ValidationAction {
	p := new(ValidationAction)
	*p = x
	return p
}

func (x ValidationAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ValidationAction) Descriptor() protoreflect.EnumDescriptor {
	return file_validatingpolicy_proto_enumTypes[1].Descriptor()
}

func (ValidationAction) Type() protoreflect.EnumType {
	return &file_validatingpolicy_proto_enumTypes[1]
}

func (x ValidationAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ValidationAction.Descriptor instead.
func (ValidationAction) EnumDescriptor() ([]byte, []int) {
	return file_validatingpolicy_proto_rawDescGZIP(), []int{1}
}

// MatchPolicyType defines resource matching behavior
type MatchPolicyType int32

const (
	MatchPolicyType_MATCH_POLICY_TYPE_UNSPECIFIED MatchPolicyType = 0
	MatchPolicyType_MATCH_POLICY_TYPE_EXACT       MatchPolicyType = 1
	MatchPolicyType_MATCH_POLICY_TYPE_EQUIVALENT  MatchPolicyType = 2
)

// Enum value maps for MatchPolicyType.
var (
	MatchPolicyType_name = map[int32]string{
		0: "MATCH_POLICY_TYPE_UNSPECIFIED",
		1: "MATCH_POLICY_TYPE_EXACT",
		2: "MATCH_POLICY_TYPE_EQUIVALENT",
	}
	MatchPolicyType_value = map[string]int32{
		"MATCH_POLICY_TYPE_UNSPECIFIED": 0,
		"MATCH_POLICY_TYPE_EXACT":       1,
		"MATCH_POLICY_TYPE_EQUIVALENT":  2,
	}
)

func (x MatchPolicyType) Enum() *MatchPolicyType {
	p := new(MatchPolicyType)
	*p = x
	return p
}

func (x MatchPolicyType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MatchPolicyType) Descriptor() protoreflect.EnumDescriptor {
	return file_validatingpolicy_proto_enumTypes[2].Descriptor()
}

func (MatchPolicyType) Type() protoreflect.EnumType {
	return &file_validatingpolicy_proto_enumTypes[2]
}

func (x MatchPolicyType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MatchPolicyType.Descriptor instead.
func (MatchPolicyType) EnumDescriptor() ([]byte, []int) {
	return file_validatingpolicy_proto_rawDescGZIP(), []int{2}
}

// ValidatingPolicySpec defines the desired behavior of the ValidatingPolicy.
type ValidatingPolicySpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// CEL expressions for validation. At least one validation or audit annotation is required.
	Validations []*Validation `protobuf:"bytes,2,rep,name=validations,proto3" json:"validations,omitempty"`
	// How to handle policy failures. Defaults to Fail.
	FailurePolicy *FailurePolicyType `protobuf:"varint,3,opt,name=failure_policy,json=failurePolicy,proto3,enum=kyverno.http.v1alpha1.FailurePolicyType,oneof" json:"failure_policy,omitempty"`
	// Conditions that must be met for validation. Maximum 64 conditions.
	MatchConditions []*MatchCondition `protobuf:"bytes,5,rep,name=match_conditions,json=matchConditions,proto3" json:"match_conditions,omitempty"`
	// Variable definitions available in policy expressions (except MatchConditions).
	Variables []*Variable `protobuf:"bytes,6,rep,name=variables,proto3" json:"variables,omitempty"`
	// Actions to take when validation fails. Required.
	ValidationActions []ValidationAction `protobuf:"varint,8,rep,packed,name=validation_actions,json=validationActions,proto3,enum=kyverno.http.v1alpha1.ValidationAction" json:"validation_actions,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ValidatingPolicySpec) Reset() {
	*x = ValidatingPolicySpec{}
	mi := &file_validatingpolicy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidatingPolicySpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidatingPolicySpec) ProtoMessage() {}

func (x *ValidatingPolicySpec) ProtoReflect() protoreflect.Message {
	mi := &file_validatingpolicy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidatingPolicySpec.ProtoReflect.Descriptor instead.
func (*ValidatingPolicySpec) Descriptor() ([]byte, []int) {
	return file_validatingpolicy_proto_rawDescGZIP(), []int{0}
}

func (x *ValidatingPolicySpec) GetValidations() []*Validation {
	if x != nil {
		return x.Validations
	}
	return nil
}

func (x *ValidatingPolicySpec) GetFailurePolicy() FailurePolicyType {
	if x != nil && x.FailurePolicy != nil {
		return *x.FailurePolicy
	}
	return FailurePolicyType_FAILURE_POLICY_TYPE_UNSPECIFIED
}

func (x *ValidatingPolicySpec) GetMatchConditions() []*MatchCondition {
	if x != nil {
		return x.MatchConditions
	}
	return nil
}

func (x *ValidatingPolicySpec) GetVariables() []*Variable {
	if x != nil {
		return x.Variables
	}
	return nil
}

func (x *ValidatingPolicySpec) GetValidationActions() []ValidationAction {
	if x != nil {
		return x.ValidationActions
	}
	return nil
}

// Validation represents a validation rule
type Validation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// CEL expression to evaluate. See: https://github.com/google/cel-spec
	Expression string `protobuf:"bytes,1,opt,name=expression,proto3" json:"expression,omitempty"`
	// Failure message. Required if expression contains line breaks.
	Message *string `protobuf:"bytes,2,opt,name=message,proto3,oneof" json:"message,omitempty"`
	// Machine-readable failure reason. Must be valid HTTP error reason.
	Reason *string `protobuf:"bytes,3,opt,name=reason,proto3,oneof" json:"reason,omitempty"`
	// CEL expression for dynamic failure messages. Takes precedence over message.
	MessageExpression *string `protobuf:"bytes,4,opt,name=message_expression,json=messageExpression,proto3,oneof" json:"message_expression,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Validation) Reset() {
	*x = Validation{}
	mi := &file_validatingpolicy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Validation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Validation) ProtoMessage() {}

func (x *Validation) ProtoReflect() protoreflect.Message {
	mi := &file_validatingpolicy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Validation.ProtoReflect.Descriptor instead.
func (*Validation) Descriptor() ([]byte, []int) {
	return file_validatingpolicy_proto_rawDescGZIP(), []int{1}
}

func (x *Validation) GetExpression() string {
	if x != nil {
		return x.Expression
	}
	return ""
}

func (x *Validation) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

func (x *Validation) GetReason() string {
	if x != nil && x.Reason != nil {
		return *x.Reason
	}
	return ""
}

func (x *Validation) GetMessageExpression() string {
	if x != nil && x.MessageExpression != nil {
		return *x.MessageExpression
	}
	return ""
}

// MatchCondition represents a condition that must be met for a request to be validated
type MatchCondition struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Qualified identifier for the condition.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// CEL expression that must evaluate to bool.
	Expression    string `protobuf:"bytes,2,opt,name=expression,proto3" json:"expression,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchCondition) Reset() {
	*x = MatchCondition{}
	mi := &file_validatingpolicy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchCondition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchCondition) ProtoMessage() {}

func (x *MatchCondition) ProtoReflect() protoreflect.Message {
	mi := &file_validatingpolicy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchCondition.ProtoReflect.Descriptor instead.
func (*MatchCondition) Descriptor() ([]byte, []int) {
	return file_validatingpolicy_proto_rawDescGZIP(), []int{2}
}

func (x *MatchCondition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MatchCondition) GetExpression() string {
	if x != nil {
		return x.Expression
	}
	return ""
}

// Variable represents a variable definition
type Variable struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique CEL identifier. Accessible as `variables.{name}`.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// CEL expression defining the variable value.
	Expression    string `protobuf:"bytes,2,opt,name=expression,proto3" json:"expression,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Variable) Reset() {
	*x = Variable{}
	mi := &file_validatingpolicy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Variable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Variable) ProtoMessage() {}

func (x *Variable) ProtoReflect() protoreflect.Message {
	mi := &file_validatingpolicy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Variable.ProtoReflect.Descriptor instead.
func (*Variable) Descriptor() ([]byte, []int) {
	return file_validatingpolicy_proto_rawDescGZIP(), []int{3}
}

func (x *Variable) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Variable) GetExpression() string {
	if x != nil {
		return x.Expression
	}
	return ""
}

// Request message for validating policy operations
type ValidatingPolicy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Spec          *ValidatingPolicySpec  `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidatingPolicy) Reset() {
	*x = ValidatingPolicy{}
	mi := &file_validatingpolicy_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidatingPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidatingPolicy) ProtoMessage() {}

func (x *ValidatingPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_validatingpolicy_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidatingPolicy.ProtoReflect.Descriptor instead.
func (*ValidatingPolicy) Descriptor() ([]byte, []int) {
	return file_validatingpolicy_proto_rawDescGZIP(), []int{4}
}

func (x *ValidatingPolicy) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ValidatingPolicy) GetSpec() *ValidatingPolicySpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

type ValidatingPolicyStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientAddress string                 `protobuf:"bytes,1,opt,name=client_address,json=clientAddress,proto3" json:"client_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidatingPolicyStreamRequest) Reset() {
	*x = ValidatingPolicyStreamRequest{}
	mi := &file_validatingpolicy_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidatingPolicyStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidatingPolicyStreamRequest) ProtoMessage() {}

func (x *ValidatingPolicyStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_validatingpolicy_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidatingPolicyStreamRequest.ProtoReflect.Descriptor instead.
func (*ValidatingPolicyStreamRequest) Descriptor() ([]byte, []int) {
	return file_validatingpolicy_proto_rawDescGZIP(), []int{5}
}

func (x *ValidatingPolicyStreamRequest) GetClientAddress() string {
	if x != nil {
		return x.ClientAddress
	}
	return ""
}

var File_validatingpolicy_proto protoreflect.FileDescriptor

const file_validatingpolicy_proto_rawDesc = "" +
	"\n" +
	"\x16validatingpolicy.proto\x12\x15kyverno.http.v1alpha1\x1a\x1egoogle/protobuf/wrappers.proto\"\xad\x03\n" +
	"\x14ValidatingPolicySpec\x12C\n" +
	"\vvalidations\x18\x02 \x03(\v2!.kyverno.http.v1alpha1.ValidationR\vvalidations\x12T\n" +
	"\x0efailure_policy\x18\x03 \x01(\x0e2(.kyverno.http.v1alpha1.FailurePolicyTypeH\x00R\rfailurePolicy\x88\x01\x01\x12P\n" +
	"\x10match_conditions\x18\x05 \x03(\v2%.kyverno.http.v1alpha1.MatchConditionR\x0fmatchConditions\x12=\n" +
	"\tvariables\x18\x06 \x03(\v2\x1f.kyverno.http.v1alpha1.VariableR\tvariables\x12V\n" +
	"\x12validation_actions\x18\b \x03(\x0e2'.kyverno.http.v1alpha1.ValidationActionR\x11validationActionsB\x11\n" +
	"\x0f_failure_policy\"\xca\x01\n" +
	"\n" +
	"Validation\x12\x1e\n" +
	"\n" +
	"expression\x18\x01 \x01(\tR\n" +
	"expression\x12\x1d\n" +
	"\amessage\x18\x02 \x01(\tH\x00R\amessage\x88\x01\x01\x12\x1b\n" +
	"\x06reason\x18\x03 \x01(\tH\x01R\x06reason\x88\x01\x01\x122\n" +
	"\x12message_expression\x18\x04 \x01(\tH\x02R\x11messageExpression\x88\x01\x01B\n" +
	"\n" +
	"\b_messageB\t\n" +
	"\a_reasonB\x15\n" +
	"\x13_message_expression\"D\n" +
	"\x0eMatchCondition\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1e\n" +
	"\n" +
	"expression\x18\x02 \x01(\tR\n" +
	"expression\">\n" +
	"\bVariable\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1e\n" +
	"\n" +
	"expression\x18\x02 \x01(\tR\n" +
	"expression\"g\n" +
	"\x10ValidatingPolicy\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12?\n" +
	"\x04spec\x18\x02 \x01(\v2+.kyverno.http.v1alpha1.ValidatingPolicySpecR\x04spec\"F\n" +
	"\x1dValidatingPolicyStreamRequest\x12%\n" +
	"\x0eclient_address\x18\x01 \x01(\tR\rclientAddress*v\n" +
	"\x11FailurePolicyType\x12#\n" +
	"\x1fFAILURE_POLICY_TYPE_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aFAILURE_POLICY_TYPE_IGNORE\x10\x01\x12\x1c\n" +
	"\x18FAILURE_POLICY_TYPE_FAIL\x10\x02*\x8a\x01\n" +
	"\x10ValidationAction\x12!\n" +
	"\x1dVALIDATION_ACTION_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16VALIDATION_ACTION_DENY\x10\x01\x12\x1b\n" +
	"\x17VALIDATION_ACTION_AUDIT\x10\x02\x12\x1a\n" +
	"\x16VALIDATION_ACTION_WARN\x10\x03*s\n" +
	"\x0fMatchPolicyType\x12!\n" +
	"\x1dMATCH_POLICY_TYPE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17MATCH_POLICY_TYPE_EXACT\x10\x01\x12 \n" +
	"\x1cMATCH_POLICY_TYPE_EQUIVALENT\x10\x022\x98\x01\n" +
	"\x17ValidatingPolicyService\x12}\n" +
	"\x18ValidatingPoliciesStream\x124.kyverno.http.v1alpha1.ValidatingPolicyStreamRequest\x1a'.kyverno.http.v1alpha1.ValidatingPolicy(\x010\x01B@Z>github.com/kyverno/kyverno-http-authorizer/apis/proto/v1alpha1b\x06proto3"

var (
	file_validatingpolicy_proto_rawDescOnce sync.Once
	file_validatingpolicy_proto_rawDescData []byte
)

func file_validatingpolicy_proto_rawDescGZIP() []byte {
	file_validatingpolicy_proto_rawDescOnce.Do(func() {
		file_validatingpolicy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_validatingpolicy_proto_rawDesc), len(file_validatingpolicy_proto_rawDesc)))
	})
	return file_validatingpolicy_proto_rawDescData
}

var file_validatingpolicy_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_validatingpolicy_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_validatingpolicy_proto_goTypes = []any{
	(FailurePolicyType)(0),                // 0: kyverno.http.v1alpha1.FailurePolicyType
	(ValidationAction)(0),                 // 1: kyverno.http.v1alpha1.ValidationAction
	(MatchPolicyType)(0),                  // 2: kyverno.http.v1alpha1.MatchPolicyType
	(*ValidatingPolicySpec)(nil),          // 3: kyverno.http.v1alpha1.ValidatingPolicySpec
	(*Validation)(nil),                    // 4: kyverno.http.v1alpha1.Validation
	(*MatchCondition)(nil),                // 5: kyverno.http.v1alpha1.MatchCondition
	(*Variable)(nil),                      // 6: kyverno.http.v1alpha1.Variable
	(*ValidatingPolicy)(nil),              // 7: kyverno.http.v1alpha1.ValidatingPolicy
	(*ValidatingPolicyStreamRequest)(nil), // 8: kyverno.http.v1alpha1.ValidatingPolicyStreamRequest
}
var file_validatingpolicy_proto_depIdxs = []int32{
	4, // 0: kyverno.http.v1alpha1.ValidatingPolicySpec.validations:type_name -> kyverno.http.v1alpha1.Validation
	0, // 1: kyverno.http.v1alpha1.ValidatingPolicySpec.failure_policy:type_name -> kyverno.http.v1alpha1.FailurePolicyType
	5, // 2: kyverno.http.v1alpha1.ValidatingPolicySpec.match_conditions:type_name -> kyverno.http.v1alpha1.MatchCondition
	6, // 3: kyverno.http.v1alpha1.ValidatingPolicySpec.variables:type_name -> kyverno.http.v1alpha1.Variable
	1, // 4: kyverno.http.v1alpha1.ValidatingPolicySpec.validation_actions:type_name -> kyverno.http.v1alpha1.ValidationAction
	3, // 5: kyverno.http.v1alpha1.ValidatingPolicy.spec:type_name -> kyverno.http.v1alpha1.ValidatingPolicySpec
	8, // 6: kyverno.http.v1alpha1.ValidatingPolicyService.ValidatingPoliciesStream:input_type -> kyverno.http.v1alpha1.ValidatingPolicyStreamRequest
	7, // 7: kyverno.http.v1alpha1.ValidatingPolicyService.ValidatingPoliciesStream:output_type -> kyverno.http.v1alpha1.ValidatingPolicy
	7, // [7:8] is the sub-list for method output_type
	6, // [6:7] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_validatingpolicy_proto_init() }
func file_validatingpolicy_proto_init() {
	if File_validatingpolicy_proto != nil {
		return
	}
	file_validatingpolicy_proto_msgTypes[0].OneofWrappers = []any{}
	file_validatingpolicy_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_validatingpolicy_proto_rawDesc), len(file_validatingpolicy_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_validatingpolicy_proto_goTypes,
		DependencyIndexes: file_validatingpolicy_proto_depIdxs,
		EnumInfos:         file_validatingpolicy_proto_enumTypes,
		MessageInfos:      file_validatingpolicy_proto_msgTypes,
	}.Build()
	File_validatingpolicy_proto = out.File
	file_validatingpolicy_proto_goTypes = nil
	file_validatingpolicy_proto_depIdxs = nil
}
